config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates_presence_of :photo
  validates_presence_of :name
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates_presence_of :comment, :rating
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

   def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: [:new, :create]


  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark p-2">
      <a href="/"><span class="navbar-brand mb-0 h1">Watch list</span></a>
      <div class="ms-auto d-flex">
        <%= link_to "My lists", lists_path, class: "btn btn-outline-light my-2 my-lg-0 ms-2" %>
        <%= link_to "Create New List", new_list_path, class: "btn btn-outline-light my-2 my-lg-0 ms-2" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions bg-dark text-center">
    <%= f.button :submit, "Confirm", class:"text-white" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="container p-2">
  <h1>My lists</h1>
  <hr>
  <% @lists.each do |list| %>
    <%= link_to list_path(list), class:'text-decoration-none' do %>
      <div class="card-list mb-3" style="background-image: url('<%= cl_image_path list.photo.key %>'); height: 300px; background-size: cover; background-position: center;">
        <h1><strong><%=list.name%></strong></h1>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <br>
  <h1>New list</h1>
  <hr>
  <%= render "form", list: @list %>
  <hr>
</div>

app/views/lists/show.html.erb
<div class="m-2" style="background-image: url('<%= cl_image_path @list.photo.key %>'); height: 300px; background-size: cover; background-position: center;">
</div>
<div class="container">
  <h1 class="flex-grow-1"><%= @list.name %></h1>
  <hr>
  <p>
    <button class="btn btn-outline-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      See reviews
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <ul>
        <% @list.reviews.each do |review|%>
        <li>
          <p><strong> <%= review.rating %> / 10 - </strong><%= review.comment %></p>
        </li>
        <% end %>
      </ul>
      <hr>
      <%= link_to "Write a review", new_list_review_path(@list), class: "btn btn-outline-dark" %>
    </div>
  </div>
  <hr>
  <h2>Movies</h2>
  <div class="container p-3 border rounded">
    <h3>Add a movie to <%= @list.name %> list</h3>
    <hr>
    <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, as: :select %>
    <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
    <%= f.submit class: "btn btn-outline-dark" %>
    <% end %>
  </div>
  <hr>
  <div class="row">
    <% @list.movies.each do |movie| %>
    <div class="col-12 col-sm-6 mb-4">
      <div class="bg-white rounded">
        <% poster_url = "https://image.tmdb.org/t/p/w500/#{movie.poster_url}" %>
        <%= image_tag poster_url, alt: movie.title, class: "poster-img" %>
        <div class="p-3 d-flex flex-column">
          <h3><%= movie.title %></h3>
          <p><em><strong><%= movie.rating %></strong> average viewers vote</em></p>
          <div class="overflow-auto" style="height:100px">
            <p><%= movie.overview %></p>
          </div>
          <hr>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <strong class="mb-1">My comment:</strong>
          <p><em><%= bookmark.comment %></em></p>
          <hr>
          <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this film?"}, class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>What do you think about this playlist ?</h1>
  <h3>Please write a fee words</h3>
  <hr>
  <%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.submit class: "btn btn-outline-dark" %>
  <% end %>
  <hr>
  <%= link_to "return to the list", list_path(@list), class: 'btn btn-dark' %>
</div>